# EMBEDDED CONTAINER PROPERTIES
server:
  port: 9091
  servlet:
    context-path: /admin

spring:
# DATASOURCE PROPERTIES
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://db:5432/turtech
    username: turtech
    password: turtechpassword
    # Keep the connection alive if idle for a long time (needed in production)
    tomcat:
      test-while-idle: true
      validation-query: SELECT 1
# JPA / HIBERNATE
  jpa:
    # Show or not log for each sql query
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        # Changing default schema for hibernate
        default_schema: turtech
        # Allows Hibernate to generate SQL optimized for a particular DBMS
        dialect: org.hibernate.dialect.PostgreSQLDialect