DROP SCHEMA IF EXISTS turtech;
CREATE SCHEMA turtech;

DROP TABLE IF EXISTS turtech.product CASCADE;

CREATE TABLE turtech.product (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  discontinued boolean NOT NULL,
  manufacturer varchar(255) DEFAULT NULL,
  category varchar(255) DEFAULT NULL,
  condition varchar(255) default null,
  description text,
  specifications text,
  in_stock_number int NOT NULL,
  list_price double precision NOT NULL,
  our_price double precision NOT NULL,
  manufacture_date varchar(255) DEFAULT NULL,
  shipping_weight double precision NOT NULL,
  "name" varchar(255) DEFAULT NULL
);

INSERT INTO turtech.product (id, discontinued, manufacturer, category, condition, 
description, specifications, in_stock_number, list_price, our_price, 
manufacture_date, shipping_weight, name)
VALUES
	(1, false, 'Apple', 'Laptops', 'New', 'Lorem ipsum dolor sit amet, 
consectetur adipisicing elit. Sapiente dicta fugit fugiat hic aliquam itaque 
facere, soluta. Totam id dolores, sint aperiam sequi pariatur praesentium animi 
perspiciatis molestias iure, ducimus!', 'Lorem ipsum dolor sit amet, consectetur 
adipisicing elit. Sapiente dicta fugit fugiat hic aliquam itaque facere, soluta. 
Totam id dolores, sint aperiam sequi pariatur praesentium animi perspiciatis 
molestias iure, ducimus!', 5, 1200.00, 999.00, '2018-10-24', 10.00, 'Apple 
McBook'),
	(2, false, 'Samsung', 'Cellphones', 'New', 'Lorem ipsum dolor sit amet, 
consectetur adipisicing elit. Sapiente dicta fugit fugiat hic aliquam itaque 
facere, soluta. Totam id dolores, sint aperiam sequi pariatur praesentium animi 
perspiciatis molestias iure, ducimus!', 'Lorem ipsum dolor sit amet, consectetur 
adipisicing elit. Sapiente dicta fugit fugiat hic aliquam itaque facere, soluta. 
Totam id dolores, sint aperiam sequi pariatur praesentium animi perspiciatis 
molestias iure, ducimus!', 5, 470.00, 390.00, '2018-10-24', 10.00, 'Samsung 
Galaxy S65'),
	(3, false, 'LG', 'Tablets', 'New', 'Lorem ipsum dolor sit amet, consectetur 
adipisicing elit. Sapiente dicta fugit fugiat hic aliquam itaque facere, soluta. 
Totam id dolores, sint aperiam sequi pariatur praesentium animi perspiciatis 
molestias iure, ducimus!', 'Lorem ipsum dolor sit amet, consectetur adipisicing 
elit. Sapiente dicta fugit fugiat hic aliquam itaque facere, soluta. Totam id 
dolores, sint aperiam sequi pariatur praesentium animi perspiciatis molestias 
iure, ducimus!', 5, 300.00, 289.00, '2018-10-24', 10.00, 'LG Tablet'),
	(4, false, 'Dell', 'Laptops', 'New', 'Lorem ipsum dolor sit amet, 
consectetur adipisicing elit. Sapiente dicta fugit fugiat hic aliquam itaque 
facere, soluta. Totam id dolores, sint aperiam sequi pariatur praesentium animi 
perspiciatis molestias iure, ducimus!', 'Lorem ipsum dolor sit amet, consectetur 
adipisicing elit. Sapiente dicta fugit fugiat hic aliquam itaque facere, soluta. 
Totam id dolores, sint aperiam sequi pariatur praesentium animi perspiciatis 
molestias iure, ducimus!', 5, 450.00, 399.00, '2018-10-24', 10.00, 'Dell 
Latitude e6230'),
	(5, false, 'Nokia', 'Cellphones', 'New', 'Lorem ipsum dolor sit amet, 
consectetur adipisicing elit. Sapiente dicta fugit fugiat hic aliquam itaque 
facere, soluta. Totam id dolores, sint aperiam sequi pariatur praesentium animi 
perspiciatis molestias iure, ducimus!', 'Lorem ipsum dolor sit amet, consectetur 
adipisicing elit. Sapiente dicta fugit fugiat hic aliquam itaque facere, soluta. 
Totam id dolores, sint aperiam sequi pariatur praesentium animi perspiciatis 
molestias iure, ducimus!', 5, 12.00, 9.00, '2018-10-24', 10.00, 'Nokia 6230'),
	(6, false, 'Apple', 'Tablets', 'New', 'Lorem ipsum dolor sit amet, 
consectetur adipisicing elit. Sapiente dicta fugit fugiat hic aliquam itaque 
facere, soluta. Totam id dolores, sint aperiam sequi pariatur praesentium animi 
perspiciatis molestias iure, ducimus!', 'Lorem ipsum dolor sit amet, consectetur 
adipisicing elit. Sapiente dicta fugit fugiat hic aliquam itaque facere, soluta. 
Totam id dolores, sint aperiam sequi pariatur praesentium animi perspiciatis 
molestias iure, ducimus!', 5, 700.00, 699.00, '2018-10-24', 10.00, 'Apple 
Ipad'),
	(7, false, 'Asus', 'Laptops', 'New', 'Lorem ipsum dolor sit amet, 
consectetur adipisicing elit. Sapiente dicta fugit fugiat hic aliquam itaque 
facere, soluta. Totam id dolores, sint aperiam sequi pariatur praesentium animi 
perspiciatis molestias iure, ducimus!', 'Lorem ipsum dolor sit amet, consectetur 
adipisicing elit. Sapiente dicta fugit fugiat hic aliquam itaque facere, soluta. 
Totam id dolores, sint aperiam sequi pariatur praesentium animi perspiciatis 
molestias iure, ducimus!', 5, 1100.00, 899.00, '2018-10-24', 10.00, 'Asus 
N61Jv'),
	(8, false, 'Meizu', 'Cellphones', 'New', 'Lorem ipsum dolor sit amet, 
consectetur adipisicing elit. Sapiente dicta fugit fugiat hic aliquam itaque 
facere, soluta. Totam id dolores, sint aperiam sequi pariatur praesentium animi 
perspiciatis molestias iure, ducimus!', 'Lorem ipsum dolor sit amet, consectetur 
adipisicing elit. Sapiente dicta fugit fugiat hic aliquam itaque facere, soluta. 
Totam id dolores, sint aperiam sequi pariatur praesentium animi perspiciatis 
molestias iure, ducimus!', 5, 300.00, 259.00, '2018-10-24', 10.00, 'Meizy M2 
Note'),
	(9, false, 'Apple', 'Tablets', 'New', 'Lorem ipsum dolor sit amet, 
consectetur adipisicing elit. Sapiente dicta fugit fugiat hic aliquam itaque 
facere, soluta. Totam id dolores, sint aperiam sequi pariatur praesentium animi 
perspiciatis molestias iure, ducimus!', 'Lorem ipsum dolor sit amet, consectetur 
adipisicing elit. Sapiente dicta fugit fugiat hic aliquam itaque facere, soluta. 
Totam id dolores, sint aperiam sequi pariatur praesentium animi perspiciatis 
molestias iure, ducimus!', 5, 600.00, 449.00, '2018-10-24', 10.00, 'Apple Ipad 
Pro'),
	(10, false, 'Acer', 'Laptops', 'New', 'Lorem ipsum dolor sit amet, 
consectetur adipisicing elit. Sapiente dicta fugit fugiat hic aliquam itaque 
facere, soluta. Totam id dolores, sint aperiam sequi pariatur praesentium animi 
perspiciatis molestias iure, ducimus!', 'Lorem ipsum dolor sit amet, consectetur 
adipisicing elit. Sapiente dicta fugit fugiat hic aliquam itaque facere, soluta. 
Totam id dolores, sint aperiam sequi pariatur praesentium animi perspiciatis 
molestias iure, ducimus!', 5, 800.00, 569.00, '2018-10-24', 10.00, 'Acer 
Laptop'),
	(11, false, 'Xiaomi', 'Cellphones', 'New', 'Lorem ipsum dolor sit amet, 
consectetur adipisicing elit. Sapiente dicta fugit fugiat hic aliquam itaque 
facere, soluta. Totam id dolores, sint aperiam sequi pariatur praesentium animi 
perspiciatis molestias iure, ducimus!', 'Lorem ipsum dolor sit amet, consectetur 
adipisicing elit. Sapiente dicta fugit fugiat hic aliquam itaque facere, soluta. 
Totam id dolores, sint aperiam sequi pariatur praesentium animi perspiciatis 
molestias iure, ducimus!', 5, 400.00, 299.00, '2018-10-24', 10.00, 'Xiaomi 
Mi2');

DROP TABLE IF EXISTS turtech.user CASCADE;

CREATE TABLE turtech.user (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email varchar(255) NOT NULL UNIQUE,
  enabled boolean NOT NULL,
  first_name varchar(255) DEFAULT NULL,
  last_name varchar(255) DEFAULT NULL,
  password varchar(255) DEFAULT NULL,
  phone varchar(255) DEFAULT NULL,
  username varchar(255) DEFAULT NULL
);

INSERT INTO turtech.user (id, email, enabled, first_name, last_name, password, phone, 
username)
VALUES
	(112,'JAdams@gmail.com',true,'John','Adams','$2a$12$zM9ElzKshw.K4tnJYSzlDOKm5BtvhShEWC7ie3RLg3UBZYm1d133u', NULL, 'user'),
	(223,'Admin@gmail.com',true,'Admin','Admin','$2a$12$zM9ElzKshw.K4tnJYSzlDOKm5BtvhShEWC7ie3RLg3UBZYm1d133u', NULL, 'admin');

DROP TABLE IF EXISTS turtech.role CASCADE;

CREATE TABLE turtech.role (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(255) DEFAULT NULL
);

INSERT INTO turtech.role (id, name)
VALUES
	(0,'ROLE_ADMIN'),
	(1,'ROLE_USER');

drop table if exists turtech.user_review cascade;

create table turtech.user_review (
	id bigint generated by default as identity primary key,
	"text" text,
	"timestamp" timestamp not null,
	user_id bigint not null references "user" (id),
	product_id bigint not null references product (id)
);

DROP TABLE IF EXISTS turtech.user_order CASCADE;

CREATE TABLE turtech.user_order (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_date timestamp DEFAULT NULL,
  order_status varchar(255) DEFAULT NULL,
  order_total decimal(19,2) DEFAULT NULL,
  shipping_date timestamp DEFAULT NULL,
  shipping_method varchar(255) DEFAULT NULL,
  billing_address_id bigint DEFAULT NULL,
  payment_id bigint DEFAULT NULL,
  shipping_address_id bigint DEFAULT NULL,
  user_id bigint DEFAULT null references "user" (id)
);

DROP TABLE IF EXISTS turtech.shopping_cart CASCADE;

CREATE TABLE turtech.shopping_cart (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  grand_total decimal(19,2) DEFAULT NULL,
  user_id bigint DEFAULT NULL REFERENCES "user" (id)
);

INSERT INTO turtech.shopping_cart (id, grand_total, user_id)
VALUES
	(112, null, 112);

DROP TABLE IF EXISTS turtech.cart_item CASCADE;

CREATE TABLE turtech.cart_item (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  qty int NOT NULL,
  subtotal decimal(19,2) DEFAULT NULL,
  product_id bigint DEFAULT NULL REFERENCES product (id),
  order_id bigint DEFAULT NULL REFERENCES user_order (id),
  shopping_cart_id bigint DEFAULT NULL REFERENCES shopping_cart (id)
);

INSERT INTO turtech.shopping_cart (id, grand_total, user_id)
VALUES
	(111,NULL,223);

DROP TABLE IF EXISTS turtech.password_reset_token;

CREATE TABLE turtech.password_reset_token (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  expiry_date timestamp DEFAULT NULL,
  token varchar(255) DEFAULT NULL,
  user_id bigint NOT NULL REFERENCES "user" (id)
);

DROP TABLE IF EXISTS turtech.payment;

CREATE TABLE turtech.payment (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  card_name varchar(255) DEFAULT NULL,
  card_number varchar(255) DEFAULT NULL,
  cvc int NOT NULL,
  default_payment boolean DEFAULT false,
  expiry_month int NOT NULL,
  expiry_year int NOT NULL,
  holder_name varchar(255) DEFAULT NULL,
  type varchar(255) DEFAULT NULL,
  order_id bigint DEFAULT NULL REFERENCES user_order (id)
);

DROP TABLE IF EXISTS turtech.shipping_address;

CREATE TABLE turtech.shipping_address (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  shipping_address_city varchar(255) DEFAULT NULL,
  shipping_address_country varchar(255) DEFAULT NULL,
  shipping_address_name varchar(255) DEFAULT NULL,
--  shipping_address_state varchar(255) DEFAULT NULL,
  shipping_address_street1 varchar(255) DEFAULT NULL,
  shipping_address_street2 varchar(255) DEFAULT NULL,
  shipping_address_zipcode varchar(255) DEFAULT NULL,
  order_id bigint DEFAULT NULL REFERENCES user_order (id)
);

DROP TABLE IF EXISTS turtech.user_payment CASCADE;

CREATE TABLE turtech.user_payment (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  card_name varchar(255) DEFAULT NULL,
  card_number varchar(255) DEFAULT NULL,
  cvc int NOT NULL,
  default_payment boolean default false,
  expiry_month int NOT NULL,
  expiry_year int NOT NULL,
  holder_name varchar(255) DEFAULT NULL,
  type varchar(255) DEFAULT NULL,
  user_id bigint DEFAULT NULL REFERENCES "user" (id)
);

DROP TABLE IF EXISTS turtech.user_billing;

CREATE TABLE turtech.user_billing (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_billing_city varchar(255) DEFAULT NULL,
  user_billing_country varchar(255) DEFAULT NULL,
  user_billing_name varchar(255) DEFAULT NULL,
--  user_billing_state varchar(255) DEFAULT NULL,
  user_billing_street1 varchar(255) DEFAULT NULL,
  user_billing_street2 varchar(255) DEFAULT NULL,
  user_billing_zipcode varchar(255) DEFAULT NULL,
  user_payment_id bigint DEFAULT NULL REFERENCES user_payment (id)
);

DROP TABLE IF EXISTS turtech.billing_address;

CREATE TABLE turtech.billing_address (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  billing_address_city varchar(255) DEFAULT NULL,
  billing_address_country varchar(255) DEFAULT NULL,
  billing_address_name varchar(255) DEFAULT NULL,
--  billing_address_state varchar(255) DEFAULT NULL,
  billing_address_street1 varchar(255) DEFAULT NULL,
  billing_address_street2 varchar(255) DEFAULT NULL,
  billing_address_zipcode varchar(255) DEFAULT NULL,
  order_id bigint DEFAULT NULL REFERENCES user_order (id)
);

DROP TABLE IF EXISTS turtech.user_role;

CREATE TABLE turtech.user_role (
  role_id int DEFAULT NULL REFERENCES role (id),
  user_id bigint DEFAULT NULL REFERENCES "user" (id),
  PRIMARY KEY (user_id, role_id)
);

INSERT INTO turtech.user_role (role_id, user_id)
VALUES
	(1,112),
	(0,223);


DROP TABLE IF EXISTS turtech.user_shipping;

CREATE TABLE turtech.user_shipping (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_shipping_city varchar(255) DEFAULT NULL,
  user_shipping_country varchar(255) DEFAULT NULL,
  user_shipping_default boolean NOT NULL,
  user_shipping_name varchar(255) DEFAULT NULL,
--  user_shipping_state varchar(255) DEFAULT NULL,
  user_shipping_street1 varchar(255) DEFAULT NULL,
  user_shipping_street2 varchar(255) DEFAULT NULL,
  user_shipping_zipcode varchar(255) DEFAULT NULL,
  user_id bigint DEFAULT NULL REFERENCES "user" (id)
);